# filepath: .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.11.0"
        
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build

      - name: Create CNAME and 404 files
        run: |
          echo 'nyuglobal.show' > dist/CNAME
          cp dist/index.html dist/404.html
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist